/* tslint:disable */
/* eslint-disable */
/*
SoundCloud Public API Specification

Discover and play over 320 million music tracks. Join the world’s largest online community of artists, bands, DJs, and audio creators.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
import { fromBuffer } from "file-type/browser"
const FormData = require("form-data")
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * RepostsApi - axios parameter creator
 * @export
 */
export const RepostsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Reposts a playlist as the authenticated user
         * @param {number} playlistId SoundCloud playlist id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        playlistAsAuthenticatedUser: async (playlistId: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'playlistId' is not null or undefined
            assertParamExists('playlistAsAuthenticatedUser', 'playlistId', playlistId)
            const localVarPath = `/reposts/playlists/{playlist_id}`
                .replace(`{${"playlist_id"}}`, encodeURIComponent(String(playlistId !== undefined ? playlistId : `-playlist_id-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication AuthHeader required
            await setApiKeyToObject({ object: localVarHeaderParameter, key: "Authorization", keyParamName: "authHeader", configuration })

    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/reposts/playlists/{playlist_id}',
                httpMethod: 'POST'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Removes a repost on a track as the authenticated user
         * @param {number} trackId SoundCloud Track id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        removeRepost: async (trackId: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'trackId' is not null or undefined
            assertParamExists('removeRepost', 'trackId', trackId)
            const localVarPath = `/reposts/tracks/{track_id}`
                .replace(`{${"track_id"}}`, encodeURIComponent(String(trackId !== undefined ? trackId : `-track_id-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication AuthHeader required
            await setApiKeyToObject({ object: localVarHeaderParameter, key: "Authorization", keyParamName: "authHeader", configuration })

    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/reposts/tracks/{track_id}',
                httpMethod: 'DELETE'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Removes a repost on a playlist as the authenticated user
         * @param {number} playlistId SoundCloud playlist id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        removeRepostOnPlaylist: async (playlistId: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'playlistId' is not null or undefined
            assertParamExists('removeRepostOnPlaylist', 'playlistId', playlistId)
            const localVarPath = `/reposts/playlists/{playlist_id}`
                .replace(`{${"playlist_id"}}`, encodeURIComponent(String(playlistId !== undefined ? playlistId : `-playlist_id-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication AuthHeader required
            await setApiKeyToObject({ object: localVarHeaderParameter, key: "Authorization", keyParamName: "authHeader", configuration })

    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/reposts/playlists/{playlist_id}',
                httpMethod: 'DELETE'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Reposts a track as the authenticated user
         * @param {number} trackId SoundCloud Track id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        trackAsAuthenticatedUser: async (trackId: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'trackId' is not null or undefined
            assertParamExists('trackAsAuthenticatedUser', 'trackId', trackId)
            const localVarPath = `/reposts/tracks/{track_id}`
                .replace(`{${"track_id"}}`, encodeURIComponent(String(trackId !== undefined ? trackId : `-track_id-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication AuthHeader required
            await setApiKeyToObject({ object: localVarHeaderParameter, key: "Authorization", keyParamName: "authHeader", configuration })

    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/reposts/tracks/{track_id}',
                httpMethod: 'POST'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * RepostsApi - functional programming interface
 * @export
 */
export const RepostsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = RepostsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Reposts a playlist as the authenticated user
         * @param {RepostsApiPlaylistAsAuthenticatedUserRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async playlistAsAuthenticatedUser(requestParameters: RepostsApiPlaylistAsAuthenticatedUserRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.playlistAsAuthenticatedUser(requestParameters.playlistId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Removes a repost on a track as the authenticated user
         * @param {RepostsApiRemoveRepostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async removeRepost(requestParameters: RepostsApiRemoveRepostRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.removeRepost(requestParameters.trackId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Removes a repost on a playlist as the authenticated user
         * @param {RepostsApiRemoveRepostOnPlaylistRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async removeRepostOnPlaylist(requestParameters: RepostsApiRemoveRepostOnPlaylistRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.removeRepostOnPlaylist(requestParameters.playlistId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Reposts a track as the authenticated user
         * @param {RepostsApiTrackAsAuthenticatedUserRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async trackAsAuthenticatedUser(requestParameters: RepostsApiTrackAsAuthenticatedUserRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.trackAsAuthenticatedUser(requestParameters.trackId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * RepostsApi - factory interface
 * @export
 */
export const RepostsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = RepostsApiFp(configuration)
    return {
        /**
         * 
         * @summary Reposts a playlist as the authenticated user
         * @param {RepostsApiPlaylistAsAuthenticatedUserRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        playlistAsAuthenticatedUser(requestParameters: RepostsApiPlaylistAsAuthenticatedUserRequest, options?: AxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.playlistAsAuthenticatedUser(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Removes a repost on a track as the authenticated user
         * @param {RepostsApiRemoveRepostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        removeRepost(requestParameters: RepostsApiRemoveRepostRequest, options?: AxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.removeRepost(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Removes a repost on a playlist as the authenticated user
         * @param {RepostsApiRemoveRepostOnPlaylistRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        removeRepostOnPlaylist(requestParameters: RepostsApiRemoveRepostOnPlaylistRequest, options?: AxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.removeRepostOnPlaylist(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Reposts a track as the authenticated user
         * @param {RepostsApiTrackAsAuthenticatedUserRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        trackAsAuthenticatedUser(requestParameters: RepostsApiTrackAsAuthenticatedUserRequest, options?: AxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.trackAsAuthenticatedUser(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for playlistAsAuthenticatedUser operation in RepostsApi.
 * @export
 * @interface RepostsApiPlaylistAsAuthenticatedUserRequest
 */
export type RepostsApiPlaylistAsAuthenticatedUserRequest = {
    
    /**
    * SoundCloud playlist id
    * @type {number}
    * @memberof RepostsApiPlaylistAsAuthenticatedUser
    */
    readonly playlistId: number
    
}

/**
 * Request parameters for removeRepost operation in RepostsApi.
 * @export
 * @interface RepostsApiRemoveRepostRequest
 */
export type RepostsApiRemoveRepostRequest = {
    
    /**
    * SoundCloud Track id
    * @type {number}
    * @memberof RepostsApiRemoveRepost
    */
    readonly trackId: number
    
}

/**
 * Request parameters for removeRepostOnPlaylist operation in RepostsApi.
 * @export
 * @interface RepostsApiRemoveRepostOnPlaylistRequest
 */
export type RepostsApiRemoveRepostOnPlaylistRequest = {
    
    /**
    * SoundCloud playlist id
    * @type {number}
    * @memberof RepostsApiRemoveRepostOnPlaylist
    */
    readonly playlistId: number
    
}

/**
 * Request parameters for trackAsAuthenticatedUser operation in RepostsApi.
 * @export
 * @interface RepostsApiTrackAsAuthenticatedUserRequest
 */
export type RepostsApiTrackAsAuthenticatedUserRequest = {
    
    /**
    * SoundCloud Track id
    * @type {number}
    * @memberof RepostsApiTrackAsAuthenticatedUser
    */
    readonly trackId: number
    
}

/**
 * RepostsApiGenerated - object-oriented interface
 * @export
 * @class RepostsApiGenerated
 * @extends {BaseAPI}
 */
export class RepostsApiGenerated extends BaseAPI {
    /**
     * 
     * @summary Reposts a playlist as the authenticated user
     * @param {RepostsApiPlaylistAsAuthenticatedUserRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RepostsApiGenerated
     */
    public playlistAsAuthenticatedUser(requestParameters: RepostsApiPlaylistAsAuthenticatedUserRequest, options?: AxiosRequestConfig) {
        return RepostsApiFp(this.configuration).playlistAsAuthenticatedUser(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Removes a repost on a track as the authenticated user
     * @param {RepostsApiRemoveRepostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RepostsApiGenerated
     */
    public removeRepost(requestParameters: RepostsApiRemoveRepostRequest, options?: AxiosRequestConfig) {
        return RepostsApiFp(this.configuration).removeRepost(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Removes a repost on a playlist as the authenticated user
     * @param {RepostsApiRemoveRepostOnPlaylistRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RepostsApiGenerated
     */
    public removeRepostOnPlaylist(requestParameters: RepostsApiRemoveRepostOnPlaylistRequest, options?: AxiosRequestConfig) {
        return RepostsApiFp(this.configuration).removeRepostOnPlaylist(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Reposts a track as the authenticated user
     * @param {RepostsApiTrackAsAuthenticatedUserRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RepostsApiGenerated
     */
    public trackAsAuthenticatedUser(requestParameters: RepostsApiTrackAsAuthenticatedUserRequest, options?: AxiosRequestConfig) {
        return RepostsApiFp(this.configuration).trackAsAuthenticatedUser(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
