/*
SoundCloud Public API Specification

Discover and play over 320 million music tracks. Join the world’s largest online community of artists, bands, DJs, and audio creators.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CommentUser } from './comment-user';

/**
 * User\'s Comment
 * @export
 * @interface Comment
 */
export interface Comment {
    /**
     * Comment body.
     * @type {string}
     * @memberof Comment
     */
    'body'?: string;
    /**
     * Created timestamp.
     * @type {string}
     * @memberof Comment
     */
    'created_at'?: string;
    /**
     * Identifier.
     * @type {number}
     * @memberof Comment
     */
    'id'?: number;
    /**
     * Kind (comment).
     * @type {string}
     * @memberof Comment
     */
    'kind'?: string;
    /**
     * User\'s identifier.
     * @type {number}
     * @memberof Comment
     */
    'user_id'?: number;
    /**
     * Timestamp.
     * @type {string}
     * @memberof Comment
     */
    'timestamp'?: string;
    /**
     * Track\'s identifier.
     * @type {number}
     * @memberof Comment
     */
    'track_id'?: number;
    /**
     * Comment\'s URL.
     * @type {string}
     * @memberof Comment
     */
    'uri'?: string;
    /**
     * 
     * @type {CommentUser}
     * @memberof Comment
     */
    'user'?: CommentUser;
}

