/*
SoundCloud Public API Specification

Discover and play over 320 million music tracks. Join the world’s largest online community of artists, bands, DJs, and audio creators.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CreateUpdatePlaylistRequestPlaylistTracksInner } from './create-update-playlist-request-playlist-tracks-inner';

/**
 * 
 * @export
 * @interface CreateUpdatePlaylistRequestPlaylist
 */
export interface CreateUpdatePlaylistRequestPlaylist {
    /**
     * Title of the playlist
     * @type {string}
     * @memberof CreateUpdatePlaylistRequestPlaylist
     */
    'title'?: string;
    /**
     * Description of the playlist
     * @type {string}
     * @memberof CreateUpdatePlaylistRequestPlaylist
     */
    'description'?: string;
    /**
     * public or private
     * @type {string}
     * @memberof CreateUpdatePlaylistRequestPlaylist
     */
    'sharing'?: CreateUpdatePlaylistRequestPlaylistSharingEnum;
    /**
     * List of tracks to add to playlist
     * @type {Array<CreateUpdatePlaylistRequestPlaylistTracksInner>}
     * @memberof CreateUpdatePlaylistRequestPlaylist
     */
    'tracks'?: Array<CreateUpdatePlaylistRequestPlaylistTracksInner>;
    /**
     * 
     * @type {Uint8Array | File | buffer.File}
     * @memberof CreateUpdatePlaylistRequestPlaylist
     */
    'artwork_data'?: Uint8Array | File | buffer.File;
    /**
     * The European Article Number
     * @type {string}
     * @memberof CreateUpdatePlaylistRequestPlaylist
     */
    'ean'?: string;
    /**
     * Playlist\'s genre
     * @type {string}
     * @memberof CreateUpdatePlaylistRequestPlaylist
     */
    'genre'?: string;
    /**
     * Label name
     * @type {string}
     * @memberof CreateUpdatePlaylistRequestPlaylist
     */
    'label_name'?: string;
    /**
     * License number
     * @type {string}
     * @memberof CreateUpdatePlaylistRequestPlaylist
     */
    'license'?: string;
    /**
     * Playlist\'s permalink
     * @type {string}
     * @memberof CreateUpdatePlaylistRequestPlaylist
     */
    'permalink'?: string;
    /**
     * Full permalink URL
     * @type {string}
     * @memberof CreateUpdatePlaylistRequestPlaylist
     */
    'permalink_url'?: string;
    /**
     * Purchase title
     * @type {string}
     * @memberof CreateUpdatePlaylistRequestPlaylist
     */
    'purchase_title'?: string;
    /**
     * Purchase URL
     * @type {string}
     * @memberof CreateUpdatePlaylistRequestPlaylist
     */
    'purchase_url'?: string;
    /**
     * Playlist\'s release
     * @type {string}
     * @memberof CreateUpdatePlaylistRequestPlaylist
     */
    'release'?: string;
    /**
     * Release date
     * @type {string}
     * @memberof CreateUpdatePlaylistRequestPlaylist
     */
    'release_date'?: string;
    /**
     * Playlist or album type
     * @type {string}
     * @memberof CreateUpdatePlaylistRequestPlaylist
     */
    'set_type'?: CreateUpdatePlaylistRequestPlaylistSetTypeEnum;
    /**
     * A comma-separated list of tags
     * @type {string}
     * @memberof CreateUpdatePlaylistRequestPlaylist
     */
    'tag_list'?: string;
}

type CreateUpdatePlaylistRequestPlaylistSharingEnum = 'public' | 'private'
type CreateUpdatePlaylistRequestPlaylistSetTypeEnum = 'album' | 'playlist'


