/*
SoundCloud Public API Specification

Discover and play over 320 million music tracks. Join the world’s largest online community of artists, bands, DJs, and audio creators.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Found
 */
export interface Found {
    /**
     * Status code.
     * @type {string}
     * @memberof Found
     */
    'status'?: string;
    /**
     * Location URL of the resource.
     * @type {string}
     * @memberof Found
     */
    'location'?: string;
}

