/*
SoundCloud Public API Specification

Discover and play over 320 million music tracks. Join the world’s largest online community of artists, bands, DJs, and audio creators.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * user\'s upload quota
 * @export
 * @interface MeQuota
 */
export interface MeQuota {
    /**
     * unlimited upload quota.
     * @type {boolean}
     * @memberof MeQuota
     */
    'unlimited_upload_quota'?: boolean;
    /**
     * upload seconds used.
     * @type {number}
     * @memberof MeQuota
     */
    'upload_seconds_used'?: number;
    /**
     * upload seconds left.
     * @type {number}
     * @memberof MeQuota
     */
    'upload_seconds_left'?: number | null;
}

