/*
SoundCloud Public API Specification

Discover and play over 320 million music tracks. Join the world’s largest online community of artists, bands, DJs, and audio creators.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { MeQuota } from './me-quota';
import { UserSubscriptionsInner } from './user-subscriptions-inner';

/**
 * SoundCloud Me object
 * @export
 * @interface Me
 */
export interface Me {
    /**
     * description.
     * @type {string}
     * @memberof Me
     */
    'description'?: string;
    /**
     * URL to a JPEG image.
     * @type {string}
     * @memberof Me
     */
    'avatar_url'?: string;
    /**
     * city.
     * @type {string}
     * @memberof Me
     */
    'city'?: string;
    /**
     * comments count. From now on, the field always has a `0` value.
     * @type {number}
     * @memberof Me
     * @deprecated
     */
    'comments_count'?: number;
    /**
     * country.
     * @type {string}
     * @memberof Me
     */
    'country'?: string;
    /**
     * created at date
     * @type {string}
     * @memberof Me
     */
    'created_at'?: string;
    /**
     * discogs name.
     * @type {string}
     * @memberof Me
     */
    'discogs_name'?: string;
    /**
     * first name.
     * @type {string}
     * @memberof Me
     */
    'first_name'?: string;
    /**
     * number of followers.
     * @type {number}
     * @memberof Me
     */
    'followers_count'?: number;
    /**
     * number of followed users.
     * @type {number}
     * @memberof Me
     */
    'followings_count'?: number;
    /**
     * first and last name.
     * @type {string}
     * @memberof Me
     */
    'full_name'?: string;
    /**
     * unique identifier
     * @type {number}
     * @memberof Me
     */
    'id'?: number;
    /**
     * kind of resource.
     * @type {string}
     * @memberof Me
     */
    'kind'?: string;
    /**
     * last modified timestamp.
     * @type {string}
     * @memberof Me
     */
    'last_modified'?: string;
    /**
     * last name.
     * @type {string}
     * @memberof Me
     */
    'last_name'?: string;
    /**
     * likes count.
     * @type {number}
     * @memberof Me
     */
    'likes_count'?: number;
    /**
     * locale.
     * @type {string}
     * @memberof Me
     */
    'locale'?: string | null;
    /**
     * online.
     * @type {boolean}
     * @memberof Me
     */
    'online'?: boolean;
    /**
     * myspace name
     * @type {string}
     * @memberof Me
     * @deprecated
     */
    'myspace_name'?: string;
    /**
     * permalink of the resource.
     * @type {string}
     * @memberof Me
     */
    'permalink'?: string;
    /**
     * URL to the SoundCloud.com page.
     * @type {string}
     * @memberof Me
     */
    'permalink_url'?: string;
    /**
     * subscription plan of the user.
     * @type {string}
     * @memberof Me
     */
    'plan'?: string;
    /**
     * number of public playlists.
     * @type {number}
     * @memberof Me
     */
    'playlist_count'?: number;
    /**
     * boolean if email is confirmed.
     * @type {boolean}
     * @memberof Me
     */
    'primary_email_confirmed'?: boolean;
    /**
     * number of private playlists.
     * @type {number}
     * @memberof Me
     */
    'private_playlists_count'?: number;
    /**
     * number of private tracks.
     * @type {number}
     * @memberof Me
     */
    'private_tracks_count'?: number;
    /**
     * number of favorited public tracks
     * @type {number}
     * @memberof Me
     */
    'public_favorites_count'?: number;
    /**
     * 
     * @type {MeQuota}
     * @memberof Me
     */
    'quota'?: MeQuota;
    /**
     * number of reposts from user
     * @type {number}
     * @memberof Me
     */
    'reposts_count'?: number;
    /**
     * a list subscriptions associated with the user
     * @type {Array<UserSubscriptionsInner>}
     * @memberof Me
     */
    'subscriptions'?: Array<UserSubscriptionsInner>;
    /**
     * number of public tracks.
     * @type {number}
     * @memberof Me
     */
    'track_count'?: number;
    /**
     * upload seconds left.
     * @type {number}
     * @memberof Me
     */
    'upload_seconds_left'?: number | null;
    /**
     * API resource URL.
     * @type {string}
     * @memberof Me
     */
    'uri'?: string;
    /**
     * username
     * @type {string}
     * @memberof Me
     */
    'username'?: string;
    /**
     * a URL to the website.
     * @type {string}
     * @memberof Me
     */
    'website'?: string;
    /**
     * a custom title for the website.
     * @type {string}
     * @memberof Me
     */
    'website_title'?: string;
}

