/*
SoundCloud Public API Specification

Discover and play over 320 million music tracks. Join the world’s largest online community of artists, bands, DJs, and audio creators.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface OAuthToken
 */
export interface OAuthToken {
    /**
     * One of `authorization_code`, `client_credentials`, `refresh_token`
     * @type {string}
     * @memberof OAuthToken
     */
    'grant_type': OAuthTokenGrantTypeEnum;
    /**
     * Client ID
     * @type {string}
     * @memberof OAuthToken
     */
    'client_id': string;
    /**
     * Client secret
     * @type {string}
     * @memberof OAuthToken
     */
    'client_secret': string;
    /**
     * Authorization code. Required on `grant_type = authorization_code`.
     * @type {string}
     * @memberof OAuthToken
     */
    'code'?: string;
    /**
     * Redirect URI. Required on `grant_type = (authorization_code|refresh_token)`.
     * @type {string}
     * @memberof OAuthToken
     */
    'redirect_uri'?: string;
    /**
     * Refresh token. Required on `grant_type = refresh_token`.
     * @type {string}
     * @memberof OAuthToken
     */
    'refresh_token'?: string;
}

type OAuthTokenGrantTypeEnum = 'authorization_code' | 'refresh_token' | 'client_credentials'


