/*
SoundCloud Public API Specification

Discover and play over 320 million music tracks. Join the world’s largest online community of artists, bands, DJs, and audio creators.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { User } from './user';
import { UserSubscriptionsInner } from './user-subscriptions-inner';

/**
 * 
 * @export
 * @interface PlaylistLabel
 */
export interface PlaylistLabel {
    /**
     * description
     * @type {string}
     * @memberof PlaylistLabel
     */
    'description'?: string;
    /**
     * URL to a JPEG image
     * @type {string}
     * @memberof PlaylistLabel
     */
    'avatar_url'?: string;
    /**
     * city
     * @type {string}
     * @memberof PlaylistLabel
     */
    'city'?: string;
    /**
     * country
     * @type {string}
     * @memberof PlaylistLabel
     */
    'country'?: string;
    /**
     * discogs name
     * @type {string}
     * @memberof PlaylistLabel
     */
    'discogs_name'?: string;
    /**
     * first name
     * @type {string}
     * @memberof PlaylistLabel
     */
    'first_name'?: string;
    /**
     * number of followers
     * @type {number}
     * @memberof PlaylistLabel
     */
    'followers_count'?: number;
    /**
     * number of followed users
     * @type {number}
     * @memberof PlaylistLabel
     */
    'followings_count'?: number;
    /**
     * first and last name
     * @type {string}
     * @memberof PlaylistLabel
     */
    'full_name'?: string;
    /**
     * unique identifier
     * @type {number}
     * @memberof PlaylistLabel
     */
    'id'?: number;
    /**
     * kind of resource
     * @type {string}
     * @memberof PlaylistLabel
     */
    'kind'?: string;
    /**
     * profile creation datetime
     * @type {string}
     * @memberof PlaylistLabel
     */
    'created_at'?: string;
    /**
     * last modified datetime
     * @type {string}
     * @memberof PlaylistLabel
     */
    'last_modified'?: string;
    /**
     * last name
     * @type {string}
     * @memberof PlaylistLabel
     */
    'last_name'?: string;
    /**
     * myspace name
     * @type {string}
     * @memberof PlaylistLabel
     * @deprecated
     */
    'myspace_name'?: string;
    /**
     * permalink of the resource
     * @type {string}
     * @memberof PlaylistLabel
     */
    'permalink'?: string;
    /**
     * URL to the SoundCloud.com page
     * @type {string}
     * @memberof PlaylistLabel
     */
    'permalink_url'?: string;
    /**
     * subscription plan of the user
     * @type {string}
     * @memberof PlaylistLabel
     */
    'plan'?: string;
    /**
     * number of public playlists
     * @type {number}
     * @memberof PlaylistLabel
     */
    'playlist_count'?: number;
    /**
     * number of favorited public tracks
     * @type {number}
     * @memberof PlaylistLabel
     */
    'public_favorites_count'?: number;
    /**
     * number of reposts from user
     * @type {number}
     * @memberof PlaylistLabel
     */
    'reposts_count'?: number;
    /**
     * number of public tracks
     * @type {number}
     * @memberof PlaylistLabel
     */
    'track_count'?: number;
    /**
     * API resource URL
     * @type {string}
     * @memberof PlaylistLabel
     */
    'uri'?: string;
    /**
     * username
     * @type {string}
     * @memberof PlaylistLabel
     */
    'username'?: string;
    /**
     * a URL to the website
     * @type {string}
     * @memberof PlaylistLabel
     */
    'website'?: string;
    /**
     * a custom title for the website
     * @type {string}
     * @memberof PlaylistLabel
     */
    'website_title'?: string;
    /**
     * a list subscriptions associated with the user
     * @type {Array<UserSubscriptionsInner>}
     * @memberof PlaylistLabel
     * @deprecated
     */
    'subscriptions'?: Array<UserSubscriptionsInner>;
}

