/*
SoundCloud Public API Specification

Discover and play over 320 million music tracks. Join the world’s largest online community of artists, bands, DJs, and audio creators.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CreateUpdatePlaylistFormRequest } from './create-update-playlist-form-request';

/**
 * 
 * @export
 * @interface PlaylistsCreateNewPlaylistRequest
 */
export interface PlaylistsCreateNewPlaylistRequest {
    /**
     * 
     * @type {string}
     * @memberof PlaylistsCreateNewPlaylistRequest
     */
    'playlist[title]': string;
    /**
     * 
     * @type {string}
     * @memberof PlaylistsCreateNewPlaylistRequest
     */
    'playlist[sharing]'?: PlaylistsCreateNewPlaylistRequestPlaylistSharingEnum;
    /**
     * 
     * @type {string}
     * @memberof PlaylistsCreateNewPlaylistRequest
     */
    'playlist[description]'?: string;
    /**
     * To pass multiple tracks, pass multiple comma-separated values, e.g. -F \"playlist[tracks][][id]=111,222\"
     * @type {string}
     * @memberof PlaylistsCreateNewPlaylistRequest
     */
    'playlist[tracks][][id]'?: string;
    /**
     * 
     * @type {Uint8Array | File | buffer.File}
     * @memberof PlaylistsCreateNewPlaylistRequest
     */
    'playlist[artwork_data]'?: Uint8Array | File | buffer.File;
    /**
     * 
     * @type {string}
     * @memberof PlaylistsCreateNewPlaylistRequest
     */
    'playlist[ean]'?: string;
    /**
     * 
     * @type {string}
     * @memberof PlaylistsCreateNewPlaylistRequest
     */
    'playlist[genre]'?: string;
    /**
     * 
     * @type {string}
     * @memberof PlaylistsCreateNewPlaylistRequest
     */
    'playlist[label_name]'?: string;
    /**
     * 
     * @type {string}
     * @memberof PlaylistsCreateNewPlaylistRequest
     */
    'playlist[license]'?: string;
    /**
     * 
     * @type {string}
     * @memberof PlaylistsCreateNewPlaylistRequest
     */
    'playlist[permalink]'?: string;
    /**
     * 
     * @type {string}
     * @memberof PlaylistsCreateNewPlaylistRequest
     */
    'playlist[permalink_url]'?: string;
    /**
     * 
     * @type {string}
     * @memberof PlaylistsCreateNewPlaylistRequest
     */
    'playlist[purchase_title]'?: string;
    /**
     * 
     * @type {string}
     * @memberof PlaylistsCreateNewPlaylistRequest
     */
    'playlist[purchase_url]'?: string;
    /**
     * 
     * @type {string}
     * @memberof PlaylistsCreateNewPlaylistRequest
     */
    'playlist[release]'?: string;
    /**
     * 
     * @type {string}
     * @memberof PlaylistsCreateNewPlaylistRequest
     */
    'playlist[release_date]'?: string;
    /**
     * 
     * @type {string}
     * @memberof PlaylistsCreateNewPlaylistRequest
     */
    'playlist[set_type]'?: PlaylistsCreateNewPlaylistRequestPlaylistSetTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof PlaylistsCreateNewPlaylistRequest
     */
    'playlist[tag_list]'?: string;
}

type PlaylistsCreateNewPlaylistRequestPlaylistSharingEnum = 'public' | 'private'
type PlaylistsCreateNewPlaylistRequestPlaylistSetTypeEnum = 'album' | 'playlist'


