/*
SoundCloud Public API Specification

Discover and play over 320 million music tracks. Join the world’s largest online community of artists, bands, DJs, and audio creators.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface SearchByQueryCreatedAtParameter
 */
export interface SearchByQueryCreatedAtParameter {
    /**
     * (yyyy-mm-dd hh:mm:ss) return tracks created at this date or later
     * @type {string}
     * @memberof SearchByQueryCreatedAtParameter
     */
    'from'?: string;
    /**
     * (yyyy-mm-dd hh:mm:ss) return tracks created at this date or earlier
     * @type {string}
     * @memberof SearchByQueryCreatedAtParameter
     */
    'to'?: string;
}

