/*
SoundCloud Public API Specification

Discover and play over 320 million music tracks. Join the world’s largest online community of artists, bands, DJs, and audio creators.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { User } from './user';
import { UserSubscriptionsInner } from './user-subscriptions-inner';

/**
 * 
 * @export
 * @interface TrackUser
 */
export interface TrackUser {
    /**
     * description
     * @type {string}
     * @memberof TrackUser
     */
    'description'?: string;
    /**
     * URL to a JPEG image
     * @type {string}
     * @memberof TrackUser
     */
    'avatar_url'?: string;
    /**
     * city
     * @type {string}
     * @memberof TrackUser
     */
    'city'?: string;
    /**
     * country
     * @type {string}
     * @memberof TrackUser
     */
    'country'?: string;
    /**
     * discogs name
     * @type {string}
     * @memberof TrackUser
     */
    'discogs_name'?: string;
    /**
     * first name
     * @type {string}
     * @memberof TrackUser
     */
    'first_name'?: string;
    /**
     * number of followers
     * @type {number}
     * @memberof TrackUser
     */
    'followers_count'?: number;
    /**
     * number of followed users
     * @type {number}
     * @memberof TrackUser
     */
    'followings_count'?: number;
    /**
     * first and last name
     * @type {string}
     * @memberof TrackUser
     */
    'full_name'?: string;
    /**
     * unique identifier
     * @type {number}
     * @memberof TrackUser
     */
    'id'?: number;
    /**
     * kind of resource
     * @type {string}
     * @memberof TrackUser
     */
    'kind'?: string;
    /**
     * profile creation datetime
     * @type {string}
     * @memberof TrackUser
     */
    'created_at'?: string;
    /**
     * last modified datetime
     * @type {string}
     * @memberof TrackUser
     */
    'last_modified'?: string;
    /**
     * last name
     * @type {string}
     * @memberof TrackUser
     */
    'last_name'?: string;
    /**
     * myspace name
     * @type {string}
     * @memberof TrackUser
     * @deprecated
     */
    'myspace_name'?: string;
    /**
     * permalink of the resource
     * @type {string}
     * @memberof TrackUser
     */
    'permalink'?: string;
    /**
     * URL to the SoundCloud.com page
     * @type {string}
     * @memberof TrackUser
     */
    'permalink_url'?: string;
    /**
     * subscription plan of the user
     * @type {string}
     * @memberof TrackUser
     */
    'plan'?: string;
    /**
     * number of public playlists
     * @type {number}
     * @memberof TrackUser
     */
    'playlist_count'?: number;
    /**
     * number of favorited public tracks
     * @type {number}
     * @memberof TrackUser
     */
    'public_favorites_count'?: number;
    /**
     * number of reposts from user
     * @type {number}
     * @memberof TrackUser
     */
    'reposts_count'?: number;
    /**
     * number of public tracks
     * @type {number}
     * @memberof TrackUser
     */
    'track_count'?: number;
    /**
     * API resource URL
     * @type {string}
     * @memberof TrackUser
     */
    'uri'?: string;
    /**
     * username
     * @type {string}
     * @memberof TrackUser
     */
    'username'?: string;
    /**
     * a URL to the website
     * @type {string}
     * @memberof TrackUser
     */
    'website'?: string;
    /**
     * a custom title for the website
     * @type {string}
     * @memberof TrackUser
     */
    'website_title'?: string;
    /**
     * a list subscriptions associated with the user
     * @type {Array<UserSubscriptionsInner>}
     * @memberof TrackUser
     * @deprecated
     */
    'subscriptions'?: Array<UserSubscriptionsInner>;
}

