/*
SoundCloud Public API Specification

Discover and play over 320 million music tracks. Join the world’s largest online community of artists, bands, DJs, and audio creators.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { TracksCreateCommentRequestCommentTimestamp } from './tracks-create-comment-request-comment-timestamp';

/**
 * 
 * @export
 * @interface TracksCreateCommentRequestComment
 */
export interface TracksCreateCommentRequestComment {
    /**
     * Comment\'s content
     * @type {string}
     * @memberof TracksCreateCommentRequestComment
     */
    'body': string;
    /**
     * 
     * @type {TracksCreateCommentRequestCommentTimestamp}
     * @memberof TracksCreateCommentRequestComment
     */
    'timestamp'?: TracksCreateCommentRequestCommentTimestamp;
}

