/*
SoundCloud Public API Specification

Discover and play over 320 million music tracks. Join the world’s largest online community of artists, bands, DJs, and audio creators.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface TrackMetadataRequestTrack
 */
export interface TrackMetadataRequestTrack {
    /**
     * 
     * @type {string}
     * @memberof TrackMetadataRequestTrack
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof TrackMetadataRequestTrack
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof TrackMetadataRequestTrack
     */
    'permalink'?: string;
    /**
     * 
     * @type {string}
     * @memberof TrackMetadataRequestTrack
     */
    'sharing'?: TrackMetadataRequestTrackSharingEnum;
    /**
     * who can embed this track \"all\", \"me\", or \"none\"
     * @type {string}
     * @memberof TrackMetadataRequestTrack
     */
    'embeddable_by'?: TrackMetadataRequestTrackEmbeddableByEnum;
    /**
     * 
     * @type {string}
     * @memberof TrackMetadataRequestTrack
     */
    'purchase_url'?: string;
    /**
     * 
     * @type {string}
     * @memberof TrackMetadataRequestTrack
     */
    'genre'?: string;
    /**
     * The tag_list property contains a list of tags separated by spaces. Multiword tags are quoted in double quotes. We also support machine tags that follow the pattern NAMESPACE:KEY=VALUE. For example: geo:lat=43.555 camel:size=medium “machine:tag=with space” Machine tags are not revealed to the user on the track pages.
     * @type {string}
     * @memberof TrackMetadataRequestTrack
     */
    'tag_list'?: string;
    /**
     * 
     * @type {string}
     * @memberof TrackMetadataRequestTrack
     */
    'label_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof TrackMetadataRequestTrack
     */
    'release'?: string;
    /**
     * string, formatted as yyyy-mm-dd, representing release date
     * @type {string}
     * @memberof TrackMetadataRequestTrack
     */
    'release_date'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TrackMetadataRequestTrack
     */
    'streamable'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof TrackMetadataRequestTrack
     */
    'downloadable'?: boolean;
    /**
     * Possible values: no-rights-reserved, all-rights-reserved, cc-by, cc-by-nc, cc-by-nd, cc-by-sa, cc-by-nc-nd, cc-by-nc-sa
     * @type {string}
     * @memberof TrackMetadataRequestTrack
     */
    'license'?: TrackMetadataRequestTrackLicenseEnum;
    /**
     * 
     * @type {boolean}
     * @memberof TrackMetadataRequestTrack
     */
    'commentable'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof TrackMetadataRequestTrack
     */
    'isrc'?: string;
}

type TrackMetadataRequestTrackSharingEnum = 'public' | 'private'
type TrackMetadataRequestTrackEmbeddableByEnum = 'all' | 'me' | 'none'
type TrackMetadataRequestTrackLicenseEnum = 'no-rights-reserved' | 'all-rights-reserved' | 'cc-by' | 'cc-by-nc' | 'cc-by-nd' | 'cc-by-sa' | 'cc-by-nc-nd' | 'cc-by-nc-sa'


