/*
SoundCloud Public API Specification

Discover and play over 320 million music tracks. Join the world’s largest online community of artists, bands, DJs, and audio creators.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * product
 * @export
 * @interface UserSubscriptionsInnerAnyOfProduct
 */
export interface UserSubscriptionsInnerAnyOfProduct {
    /**
     * subscription id instance.
     * @type {string}
     * @memberof UserSubscriptionsInnerAnyOfProduct
     */
    'id'?: string;
    /**
     * subscription name instance.
     * @type {string}
     * @memberof UserSubscriptionsInnerAnyOfProduct
     */
    'name'?: string;
}

