/*
SoundCloud Public API Specification

Discover and play over 320 million music tracks. Join the world’s largest online community of artists, bands, DJs, and audio creators.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface WebProfilesInner
 */
export interface WebProfilesInner {
    /**
     * Link\'s title
     * @type {string}
     * @memberof WebProfilesInner
     */
    'title'?: string;
    /**
     * Timestamp of when the link was added to the profile.
     * @type {string}
     * @memberof WebProfilesInner
     */
    'created_at'?: string;
    /**
     * Id
     * @type {number}
     * @memberof WebProfilesInner
     */
    'id'?: number;
    /**
     * Kind
     * @type {string}
     * @memberof WebProfilesInner
     */
    'kind'?: string;
    /**
     * Service or platform
     * @type {string}
     * @memberof WebProfilesInner
     */
    'service'?: string;
    /**
     * URL of the external link
     * @type {string}
     * @memberof WebProfilesInner
     */
    'url'?: string;
    /**
     * Username extracted from the external link
     * @type {string}
     * @memberof WebProfilesInner
     */
    'username'?: string;
}

